# Generated by Django 5.2.3 on 2025-06-28 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('ModuleId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ModuleName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('ProgramId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ProgramName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('SemesterId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SemesterNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('LectureId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('LectureNumber', models.IntegerField()),
                ('LecturerName', models.CharField(max_length=100)),
                ('ModuleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appLogin.module')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='SemesterId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appLogin.semester'),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('BatchId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('BatchName', models.CharField(max_length=50)),
                ('ProgramId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appLogin.program')),
                ('SemesterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appLogin.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('StudentName', models.CharField(max_length=100)),
                ('BatchId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appLogin.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('AbsenceId', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('AbsenceDate', models.FloatField(default=1.0)),
                ('LectureId_id', models.ForeignKey(db_column='lecture_id', on_delete=django.db.models.deletion.CASCADE, to='appLogin.lecture')),
                ('StudentId', models.ForeignKey(db_column='student_id', on_delete=django.db.models.deletion.CASCADE, to='appLogin.student')),
            ],
        ),
    ]
